### ISSUE TITLE
elasticsearch2: add support for searchguard2

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#1221]
We would like to use [searchguard2](https://github.com/floragunncom/search-guard) as an alternative to shield. Any of the following options should be available:
1. Using `client-mode(http)` provided https is possible
2. Using `client-mode(node)` [should work](/floragunncom/search-guard/issues/128)
3. Using transport mode: this seems to be pushed by elastic in favor of node/client (sensed to be deprecated in the near future)

I already tested 1. but I'm getting the following sg error: `SSL Problem Received fatal alert: certificate_unknown`

I also tested 2. using the following config (using `elasticsearch2(resource("/path/to/elasticsearch.yml")))

```

---
cluster:
  name: elasticsearch
node:
  client: true
  name: syslog_ng
path:
  data: /tmp
  home: /tmp
http:
  enabled: false
searchguard:
  ssl:
    transport:
      enabled: true
      keystore_filepath: "/etc/syslog-ng/elasticsearch/node-1-keystore.jks"
      keystore_password: changeit
      truststore_filepath: "/etc/syslog-ng/elasticsearch/truststore.jks"
      truststore_password: changeit
      enforce_hostname_verification: false
    http:
      enabled: false
  audit:
    type: internal_elasticsearch
  authcz:
    admin_dn:
      - CN=sgadmin
```

Here's the error message:

```
[WARN ][com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport] [T-Ray] Someone speaks plaintext instead of ssl, will close the channel
```

Maybe @floragunncom could kindly comment?

Thanks!
